### ISSUE TITLE
Downcase all widget text by default.

### ISSUE THREAD

**Issue by david** [mojotech/dill#46]
But allow access to the original text.

**Comment by adsteel** [comment]
@david This would leave open challenge of something like this:

```ruby
widget(:form).select = 'USA'
widget(:form).select == 'USA' # => false
widget(:form).select == 'usa' # => true
```

Are there certain methods that we want to make sure are always downcased, like `to_table`, while leaving the rest untouched?

**Comment by david** [comment]
@adsteel That makes sense. `#to_table` is definitely the most important one of them.

**Comment by adsteel** [comment]
@david I explored the downcasing option, but I couldn't figure out a way to always downcase that wouldn't violate the element of least surprise, like in the example above.

**Comment by adsteel** [comment]
Closing in favor of case-insensitive table matching via https://github.com/mojotech/dill/pull/121
