### ISSUE TITLE
Allow specifying a default value for a widget that is absent

### ISSUE THREAD

**Issue by david** [mojotech/dill#58]
widget <name>, ..., absent: 'some value'

**Comment by adsteel** [comment]
@david Would this look something like this?

```ruby
widget :button, '.button', absent: 'Missing button'

...

expect(roles.user.widget(:button)).to eq('Missing button')
```

**Comment by david** [comment]
Either that or `default`, but yes, that's the idea.

**Comment by david** [comment]
However, I haven't needed this much, so I wonder how useful it really would be.

**Comment by adsteel** [comment]
It seems like this use case could also be addressed with `visible?`

**Comment by david** [comment]
Probably, yes.

**Comment by adsteel** [comment]
Would you be in favor of closing this issue for now, then?

**Comment by david** [comment]
Sure.
