### ISSUE TITLE
consider adding this to dill core

### ISSUE THREAD

**Issue by samccone** [mojotech/dill#79]
https://github.com/jnicklas/capybara/issues/29

to fix cross browser alert text testing

```ruby
 def check_alert(text)
    page.evaluate_script "window.original_alert_function = window.alert"
    page.evaluate_script "window.alert = function(msg) { window.lastAlertMsg = msg; }"
    yield
    last_alert_msg = page.evaluate_script "window.lastAlertMsg"
    last_alert_msg.should == text
  ensure
    page.evaluate_script "window.alert = window.original_alert_function"
  end
```

**Comment by adsteel** [comment]
@samccone Looks like this has been addressed in Capybara core. https://github.com/jnicklas/capybara/blob/d087965f8110f4098a11f52bb18edea88df277ac/lib/capybara/session.rb#L549

**Comment by samccone** [comment]
sweet

**Comment by samccone** [comment]
I am not sure however if there is a way to test the text of the alert yet, however I have not dug in

**Comment by adsteel** [comment]
@samccone It looks like `accept_modal` and variants return the modal text. https://github.com/jnicklas/capybara#modals

**Comment by samccone** [comment]
Accepting the modal was not my issue here. It was verifying the alert text and asserting the contents. But heh no biggie

**Comment by samccone** [comment]
But yeah the new way to capture the text seems like it should work  🐴👏🗿
