### ISSUE TITLE
Add a simple example for tagged behavior

### ISSUE THREAD

**Issue by samccone** [mojotech/dill#81]
This information is very hard to find online

```rb
Before('@cats') do
  CATS="meow"
end
```

This is not dill core* But I think in bringing this to market having this information around is critical for Dill to be the defacto tool

**Comment by adsteel** [comment]
@samccone Could you explain how this is Dill's domain rather than Cucumber's? ie How this is different from https://github.com/cucumber/cucumber/wiki/Hooks ?

**Comment by samccone** [comment]
Yep I think in 2013 that wiki page was way less good
