### ISSUE TITLE
select widget returns incorrect value

### ISSUE THREAD

**Issue by murtys** [mojotech/dill#85]
It looks like the widget is returning values associated with the option element that has the 'selected' attribute, rather than the value that is currently set on the select element.

**Comment by adsteel** [comment]
I'm having a similar issue. After selecting a specific option (with no options given a 'selected' attribute), a binding.pry reveals:

```ruby
widget(name).widget(field).root['selected'] #=> nil
widget(name).widget(field).get #=> nil
```

The correct option is selected in the browser, and is returned with javascript as expected.

**Comment by david** [comment]
Sigh. There aren't enough hours in the day for everything I need to do. Want to take a stab at fixing this @adsteel?

**Comment by adsteel** [comment]
@david It's officially on my list for MojoTime. I want to flesh out the docs as much as possible first, but then I think I'll start looking at some of these issues with you.

**Comment by adsteel** [comment]
Some finding from my foray this evening:

I was unable to reproduce this problem in the existing Dill tests. However, using the same technique I tried in the Dill tests, I <i>was</i> able to reproduce this problem in a Cucumber test with Capybara-Webkit and the Selenium Chrome Driver.

Here's a simplified version of the Dill.

```ruby
form :example_form, 'form' do
  text_field :message, 'message'
  select :subject, 'subject'
end

def submit_form
  params = {
    message: 'This is a test message.',
    subject: 'feedback',
  }
  widget(:example_form).set(params)
  params.each do |key, value|
    puts widget(widget_name).send(key).inspect 
  end
end
```

This output:

```unix
"This is a test message."
nil
```

**Comment by adsteel** [comment]
@david It looks like this might be a Capybara bug, not a Dill bug. Do you have any interest in taking a quick look at this commit? https://github.com/adsteel/dill/commit/f5e7501ed7b5a7b506ce9f74537950509b4110f0

**Comment by adsteel** [comment]
This is a bug in how Dill is retrieving the selected value. Calling `find('select').value` consistently returns the correct selected value across drivers. Now to implement that in Dill...

**Comment by adsteel** [comment]
Addressed here: https://github.com/mojotech/dill/pull/124
