### ISSUE TITLE
widgit(:foo).diff <cucumber:ast:table> Reporting is invalid 

### ISSUE THREAD

**Issue by samccone** [mojotech/dill#93]
![](http://dl.dropbox.com/u/36928599/Screenshots/022.png)

    cucumber (1.3.8)
    cucumber-rails (1.4.0)
    dill (0.5.2)

**Comment by adsteel** [comment]
@samccone I know this was a over a year and a half ago, but any other details, like what code triggered this failure? Was it simply calling `widget(:foo).diff <cucumber:ast:table> ?

**Comment by samccone** [comment]
no idea, closing
