### ISSUE TITLE
Make Dill compatible with Spring binstubs

### ISSUE THREAD

**Issue by cpjolicoeur** [mojotech/dill#96]

**Comment by adsteel** [comment]
@cpjolicoeur Could you elaborate?

**Comment by cpjolicoeur** [comment]
using binstubs `./bin/cucumber` doesn't play nicely with Dill.  At least not as of May 27, 2014 :)

I think if you generate binstubs on a project that uses Dill and Cucumber and try to run your tests, you will get the issue.

**Comment by adsteel** [comment]
@cpjolicoeur I wasn't able to duplicate the issue, but I gave two attempts:

1. In a client project with Dill
- `$ bundle binstubs cucumber`
- `$ bin/cucumber feature/file.feature`

2. Brand new app with Dill
- Created a new Rails project with two cucumber/dill tests, one uses selenium and one that doesn't use selenium
- `$ bundle binstubs cucumber`
- `$ bin/cucumber features/file.feature`

No issues. Seem like this issue have have resolved itself?

**Comment by adsteel** [comment]
Considering resolved unless someone else sees this again.
